### ISSUE TITLE
Unable to load css

### ISSUE THREAD

**Issue by syedidrus** [galojix/roster-wizard#21]
Hi, i have been receiving  this error when pressing f12. Seems like webpage cannot load the css. Can anyone help me? Thanks

![image](https://github.com/galojix/roster-wizard/assets/48024560/a73763f2-ba59-4555-80fd-29e4a236750e)

**Comment by gregcowell** [comment]
Have you been using the installation instructions [here](https://www.galojix.com/case-studies/roster/) or some other method ?

**Comment by syedidrus** [comment]
I followed the instruction for installing and deployment for single user/demo

**Comment by gregcowell** [comment]
Do you have "DEBUG=True" in .env_demo_web ?

**Comment by syedidrus** [comment]
yes, now i'm trying to run using docker desktop

**Comment by gregcowell** [comment]
I have re-tested the installation procedure on a new machine and it worked for me. I am guessing the problem is somehow related to the environment you are using. However it still may be something that should be fixed in the source code.

Could you please run `docker compose logs -f web` and check if there are any related errors ?

**Comment by gregcowell** [comment]
Also what happens when you try [http://127.0.0.1:8000/static/css/bootstrap.min.css](http://127.0.0.1:8000/static/css/bootstrap.min.css) ?

**Comment by syedidrus** [comment]
I've redeployed using docker desktop for windows, works fine. I close this issue for now
