### ISSUE TITLE
Issue in generating the shift

### ISSUE THREAD

**Issue by vaithiyanath** [galojix/roster-wizard#24]
Hi Team,

We have up the roster wizard and tried to generate the. shift for our use case, while going through your tutorail i can see max staff is missing in shift field, added the screenshot for reference also getting **Could not generate roster, ensure staff details and rules are correct...** Am i missing any thing here or did i need to add any config 

Thanks in advance 

<img width="1576" alt="Screenshot 2024-01-05 at 10 39 13 AM" src="https://github.com/galojix/roster-wizard/assets/46320125/b21c0c5d-9e0a-4244-8d99-d32ef43dfe9f">

![Screenshot 2024-01-05 at 10 39 18 AM](https://github.com/galojix/roster-wizard/assets/46320125/9cebd659-0033-4099-b8b4-321a0724d517)

**Comment by gregcowell** [comment]
The maximum staff field was removed because it is redundant. The exact number of staff required per shift is determined by the skill mix rules. Make sure you follow the user guide instead of the video. The video is just a quick demonstration of an earlier version. The user guide contains some tips for successfully generating a roster.
